### ISSUE TITLE
Erro 

### ISSUE THREAD

**Issue by raphaeldan** [mpcabete/bombcrypto-bot#129]
Alguém poderia ajudar?

- baixei o novo bot
- descompactei
- acessei a pasta através do prompt
- rodei o comando "pip install -r requirements.txt"
- resultou em que todos os requerimentos estavam atendidos
- rodei o index com o comando python.exe index.pyh
- Resultado abaixo

C:\bomb>python index.py

>>---> Press ctrl + c to kill the bot.
>>---> Some configs can be fount in the config.yaml file.

[04/12/2021 15:30:05]
 => Checking for capcha.

[04/12/2021 15:30:05]
 => checking for capcha

Traceback (most recent call last):
  File "C:\bomb\index.py", line 593, in <module>
    main()
  File "C:\bomb\index.py", line 559, in main
    solveCapcha()
  File "C:\bomb\index.py", line 208, in solveCapcha
    pieces_start_pos = getPiecesPosition()
  File "C:\bomb\index.py", line 151, in getPiecesPosition
    popup_pos = positions(robot)
  File "C:\bomb\index.py", line 327, in positions
    result = cv2.matchTemplate(img,target,cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

**Comment by raphaeldan** [comment]
baixei novamente e funcionou
