### ISSUE TITLE
ERROR: No matching distribution found for PyMsgBox==1.0.9

### ISSUE THREAD

**Issue by Tavinlol** [mpcabete/bombcrypto-bot#219]
Olá,

Estou obtendo o seguinte erro:

```
Collecting PyMsgBox==1.0.9
  Using cached PyMsgBox-1.0.9.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmpdl4zrh_9'
         cwd: C:\Users\Otávio Henrique\AppData\Local\Temp\pip-install-a6pa_zh7\pymsgbox_a1e396d055f94d9fad4fd7525ff29309
    Complete output (14 lines):
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe1 in position 0: unexpected end of data (sitecustomize.py, line 21)
    running dist_info
    creating C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.egg-info
    writing C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.egg-info\dependency_links.txt
    writing top-level names to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.egg-info\top_level.txt
    writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.py' under directory 'pymsgbox'
    writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.egg-info\SOURCES.txt'
    creating 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-l3lzhg0x\PyMsgBox.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7d/ff/4c6f31a4f08979f12a663f2aeb6c8b765d3bd592e66eaaac445f547bb875/PyMsgBox-1.0.9.tar.gz#sha256=2194227de8bff7a3d6da541848705a155dcbb2a06ee120d9f280a1d7f51263ff (from https://pypi.org/simple/pymsgbox/). Command errored out with exit status 1: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmpdl4zrh_9' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyMsgBox==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
ERROR: No matching distribution found for PyMsgBox==1.0.9
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
```
Alguem consegue me dar um caminho para resolução?

**Comment by mpcabete** [comment]
hmm tenta tirar a linha 10 do requirements (PyMsgBox==1.0.9) e ve se da certo

**Comment by Alt4s** [comment]
vamos lá: desinstalei o python e instalei o 3.9
executei o comando pip instal torch
atualizei o pip 
executei o pip install requeriments
tentei rodar  e continua aparecendo erro

![image](https://user-images.githubusercontent.com/95438518/145693386-c5b45d89-de3a-41d4-a868-fdd108477bac.png)

**Comment by Tavinlol** [comment]
Obrigado pelo retorno, gerou o erro abaixo: 

 ```
Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Users\Otávio Henrique\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmp02u8ttb5'
       cwd: C:\Users\Otávio Henrique\AppData\Local\Temp\pip-install-as1a9cic\pyscreeze_b72af66fa51e4c758550039ab2025071
  Complete output (19 lines):
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe1 in position 0: unexpected end of data (sitecustomize.py, line 21)
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
    warnings.warn(msg)
  running dist_info
  creating C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info
  writing C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\PKG-INFO
  writing dependency_links to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\dependency_links.txt
  writing requirements to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\requires.txt
  writing top-level names to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\top_level.txt
  writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.py' under directory 'pyautogui'
  adding license file 'LICENSE.txt'
  adding license file 'AUTHORS.txt'
  writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\SOURCES.txt'
  creating 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.dist-info'
  error: invalid command 'bdist_wheel'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/75/23/3edc5ee974fb3994a38095056483b5d4b82b32a81f029e8085a4b4c05317/PyScreeze-0.1.28.tar.gz#sha256=4428600ed19b30cd3f4b5d83767d198fc1dbae7439eecf9bd795445c009b67ae (from https://pypi.org/simple/pyscreeze/). Command errored out with exit status 1: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Users\Otávio Henrique\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmp02u8ttb5' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyScreeze==0.1.28 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.28)
ERROR: No matching distribution found for PyScreeze==0.1.28
```

**Comment by Tavinlol** [comment]
> hmm tenta tirar a linha 10 do requirements (PyMsgBox==1.0.9) e ve se da certo

Obrigado pelo retorno gerou o erro abaixo:

`  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Users\Otávio Henrique\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmp02u8ttb5'
       cwd: C:\Users\Otávio Henrique\AppData\Local\Temp\pip-install-as1a9cic\pyscreeze_b72af66fa51e4c758550039ab2025071
  Complete output (19 lines):
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe1 in position 0: unexpected end of data (sitecustomize.py, line 21)
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
    warnings.warn(msg)
  running dist_info
  creating C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info
  writing C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\PKG-INFO
  writing dependency_links to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\dependency_links.txt
  writing requirements to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\requires.txt
  writing top-level names to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\top_level.txt
  writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.py' under directory 'pyautogui'
  adding license file 'LICENSE.txt'
  adding license file 'AUTHORS.txt'
  writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.egg-info\SOURCES.txt'
  creating 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-9vatf2az\PyScreeze.dist-info'
  error: invalid command 'bdist_wheel'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/75/23/3edc5ee974fb3994a38095056483b5d4b82b32a81f029e8085a4b4c05317/PyScreeze-0.1.28.tar.gz#sha256=4428600ed19b30cd3f4b5d83767d198fc1dbae7439eecf9bd795445c009b67ae (from https://pypi.org/simple/pyscreeze/). Command errored out with exit status 1: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Users\Otávio Henrique\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmp02u8ttb5' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyScreeze==0.1.28 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.28)
ERROR: No matching distribution found for PyScreeze==0.1.28
`

**Comment by mpcabete** [comment]
tenta atualizar o arquivo requirements.txt q eu atualizei agora, e ve se resolve

**Comment by Alt4s** [comment]
> tenta atualizar o arquivo requirements.txt q eu atualizei agora, e ve se resolve

aeeeee, agora deu !!!!

**Comment by Tavinlol** [comment]
> tenta atualizar o arquivo requirements.txt q eu atualizei agora, e ve se resolve

Realizei novamente o download da pasta toda e rodei  pip install -r requirements.txt
Ocorreu o mesmo erro: 

```
ERROR: Could not find a version that satisfies the requirement PyMsgBox==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
ERROR: No matching distribution found for PyMsgBox==1.0.9
```

Removendo a linha do PyMsgBox gerou o erro:

```
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Users\Otávio Henrique\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmp5kp40tsj'
       cwd: C:\Users\Otávio Henrique\AppData\Local\Temp\pip-install-g2j9vcim\pyscreeze_da3398a9cb8b47a5b360e55425c7b154
  Complete output (19 lines):
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe1 in position 0: unexpected end of data (sitecustomize.py, line 21)
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
    warnings.warn(msg)
  running dist_info
  creating C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info
  writing C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info\PKG-INFO
  writing dependency_links to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info\dependency_links.txt
  writing requirements to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info\requires.txt
  writing top-level names to C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info\top_level.txt
  writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.py' under directory 'pyautogui'
  adding license file 'LICENSE.txt'
  adding license file 'AUTHORS.txt'
  writing manifest file 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.egg-info\SOURCES.txt'
  creating 'C:\Users\Otávio Henrique\AppData\Local\Temp\pip-modern-metadata-i4j3wqw8\PyScreeze.dist-info'
  error: invalid command 'bdist_wheel'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/75/23/3edc5ee974fb3994a38095056483b5d4b82b32a81f029e8085a4b4c05317/PyScreeze-0.1.28.tar.gz#sha256=4428600ed19b30cd3f4b5d83767d198fc1dbae7439eecf9bd795445c009b67ae (from https://pypi.org/simple/pyscreeze/). Command errored out with exit status 1: 'C:\Users\Otávio Henrique\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' 'C:\Users\Otávio Henrique\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\OTVIOH~1\AppData\Local\Temp\tmp5kp40tsj' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyScreeze==0.1.28 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.28)
ERROR: No matching distribution found for PyScreeze==0.1.28
```
Tentei remover a linha PyScreeze e executou a instalação com sucesso:

Successfully installed PyAutoGUI-0.9.53 mss-6.1.0 opencv-python-4.5.4.60

Porém por conta destas dependencias que faltam não executa o bot 

```
C:\Users\Otávio Henrique\Downloads\bombcrypto-bot-main (4)\bombcrypto-bot-main>python index.py
Traceback (most recent call last):
  File "C:\Users\Otávio Henrique\Downloads\bombcrypto-bot-main (4)\bombcrypto-bot-main\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\Users\Otávio Henrique\Downloads\bombcrypto-bot-main (4)\bombcrypto-bot-main\captcha\solveCaptcha.py", line 3, in <module>
    import pyautogui
  File "C:\Users\Otávio Henrique\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'
```

**Comment by Tavinlol** [comment]
Baixei em outra maquina e rodou o bot, obrigado.

**Comment by WanaColacio** [comment]
![image](https://user-images.githubusercontent.com/95771077/146585120-9c46400c-669f-4dea-aa42-a59e806b13cb.png)
meu erro desse persiste, meu python e o 3.9.9

**Comment by japcorrea1** [comment]
> ![image](https://user-images.githubusercontent.com/95771077/146585120-9c46400c-669f-4dea-aa42-a59e806b13cb.png) meu erro desse persiste, meu python e o 3.9.9

mesmo erro no meu, conseguiu resolver? preciso de uma luz
