### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'hub'

### ISSUE THREAD

**Issue by lpstyle** [mpcabete/bombcrypto-bot#225]
Galera to recebendo o seguinte erro.

```
c:\bomb>python index.py
Traceback (most recent call last):
  File "c:\bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "c:\bomb\captcha\solveCaptcha.py", line 13, in <module>
    model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local')
AttributeError: module 'torch' has no attribute 'hub'
```

**Comment by mpcabete** [comment]
tenta
`pip install torch --upgrade`

**Comment by lpstyle** [comment]
Nada o erro continua, vou tentar reinstalar o python aqui.

**Comment by MauMorhy** [comment]
> pip install torch --upgrade

Conseguiu resolver? Estou com esse problema!
