### ISSUE TITLE
Como resolver erros de instalação do torch | How to solve error in torch install

### ISSUE THREAD

**Issue by Nucito** [mpcabete/bombcrypto-bot#229]
**Português**

> 1 - Veja a versão do seu python.
> Se ele estiver em qualquer versão acima da 3.9.x ele não vai rodar pois o torch não foi atualizado.
> 
> 2 - Se o torch mesmo assim estiver com problema recomendo instalar em uma virtualenv para saber se o problema se trata de uma incompatibilidade com algum dos seus pacotes instalados.
> 
> 3 - Se mesmo assim o seu torch não conseguir ser instalado recomendo que desinstale o seu python completamente e tente reinstalar novamente.

**English**

> 1 - See your python version.
> If it is on any version above 3.9.x it will not run as the torch has not been updated.
> 
> 2 - If the torch is still having a problem, I recommend installing it on a virtualenv to find out if the problem is an incompatibility with one of your installed packages.
> 
> 3 - If your torch still fails to be installed, I recommend that you uninstall your python completely and try to reinstall again.

**Comment by rnesheiksilvestre** [comment]
![Captura de Tela 2021-12-11 às 19 40 13](https://user-images.githubusercontent.com/39178767/145693815-9de59e17-b31a-42b2-b216-70622dde3b3e.png)

**Comment by Nucito** [comment]
> ![Captura de Tela 2021-12-11 às 19 40 13](https://user-images.githubusercontent.com/39178767/145693815-9de59e17-b31a-42b2-b216-70622dde3b3e.png) ele baixa mas n instala

Qual seria as configurações do seu pc?

**Comment by EoAraujo** [comment]
**1 - Veja a versão do seu python.
Se ele estiver em qualquer versão acima da 3.9.x ele não vai rodar pois o torch não foi atualizado.**

Essa dica funcionou absurdos aqui, estava usando o python 3.10.1 e dava erro na instalação do torch coloquei a versão 3.9.9
e funcionou corretamente

**Comment by rnesheiksilvestre** [comment]
> > ![Captura de Tela 2021-12-11 às 19 40 13](https://user-images.githubusercontent.com/39178767/145693815-9de59e17-b31a-42b2-b216-70622dde3b3e.png) ele baixa mas n instala
> 
> Qual seria as configurações do seu pc?

é um notebook i5-1035g1 20gb ram está com mac os ai coloco na vm

**Comment by CorreiaDeveloper** [comment]
Em resumo preciso baixar a versao do Python em 3.0.9 ou inferior?

**Comment by Nucito** [comment]
@rnesheiksilvestre Ja deu uma olhada no consumo de escrita do seu disco como ele? as vezes ele esta atingindo um consumo muito grande e não consegue terminar

**Comment by Nucito** [comment]
> Em resumo preciso baixar a versao do Python em 3.0.9 ou inferior?

Isso mesmo😁

**Comment by mtmassa** [comment]
> Em resumo preciso baixar a versao do Python em 3.0.9 ou inferior?

aqui deu certo instalando o 3.9.9 e o visual studio.

**Comment by Nucito** [comment]
Apenas com isso vc ja vai conseguir rodar tranquilamente 😁
[Build Tools](https://go.microsoft.com/fwlink/?LinkId=691126)

**Comment by paulocba** [comment]
> Apenas com isso vc ja vai conseguir rodar tranquilamente 😁 [Build Tools](https://go.microsoft.com/fwlink/?LinkId=691126)

nao consigo instalar o app do link.. algum instalador offline disponivel pra fortalecer ai?

**Comment by rnesheiksilvestre** [comment]
> @rnesheiksilvestre Ja deu uma olhada no consumo de escrita do seu disco como ele? as vezes ele esta atingindo um consumo muito grande e não consegue terminar

subi os core e a memoria da vm conseguir instalar obrigado

**Comment by LoboNFT** [comment]
@rnesheiksilvestre o meu ta dando isso, ja instalei versao 3.8.x do python, uso o mac os
![Captura de Tela 2021-12-11 às 22 03 34](https://user-images.githubusercontent.com/95582054/145696623-6eb882df-e6c9-4eb6-9428-e0f05ea52d31.png)
o

**Comment by rnesheiksilvestre** [comment]
> 

pow mano eu n conseguir usar no mac os não fiz uma vm
![Uploading Captura de Tela 2021-12-11 às 22.07.04.png…]()

**Comment by LoboNFT** [comment]
qual programa vc indica para fazer vm pra mac os que seja free?

**Comment by rnesheiksilvestre** [comment]
> qual programa vc indica para fazer vm pra mac os que seja free?

Vmware so baixa crackeado

**Comment by Nucito** [comment]
> > @rnesheiksilvestre Ja deu uma olhada no consumo de escrita do seu disco como ele? as vezes ele esta atingindo um consumo muito grande e não consegue terminar
> 
> subi os core e a memoria da vm conseguir instalar obrigado

Que bom que conseguiu😁

**Comment by Nucito** [comment]
> qual programa vc indica para fazer vm pra mac os que seja free?

Virtualbox ou HyperV

**Comment by HotmailToper** [comment]
Boa noite galera

aqui da o seguinte depois de tudo instalado e estar na versão 3.9.6 do python, eis o problema:
Traceback (most recent call last):
  File "C:\Users\Tony SSD\bombcrypto-bot\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\Users\Tony SSD\bombcrypto-bot\captcha\solveCaptcha.py", line 13, in <module>
    model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local')
AttributeError: module 'torch' has no attribute 'hub'

o que acham que pode ser?

**Comment by kalleldf** [comment]
Estou com o seguinte erro:

No matching distribution found for torch 1.10.0

Estou usando o Python 3.9.9 fiz o procedimento todo no outro pc e deu certo mas no notebook não está funcionando.

**Comment by Gaboo134** [comment]
boa noite primeiramente obrigado pela distribuição, após o captcha com código 514 o bot demorou para responder em seguida respondeu e deslogou, oque pode ser 

![image](https://user-images.githubusercontent.com/95483887/145698471-e96b9200-7f84-450a-954b-6c57010ffffd.png)

**Comment by Diegoarend** [comment]
Galera, além de instalar o python em versão abaixo da 3.10 creio que tbm precise instalar na versão 64bits pois é a versão que o torch tem como base.

**Comment by cryptocanja** [comment]
meu erro é esse na VM > ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device
é porque não tem espaço de disco será?

**Comment by LoboNFT** [comment]
> meu erro é esse na VM > ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device é porque não tem espaço de disco será?

sim

**Comment by cryptocanja** [comment]
> > meu erro é esse na VM > ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device é porque não tem espaço de disco será?
> 
> sim

sabe se tem como aumentar o disco da google cloud ? ou vou ter que criar outra

**Comment by Gaboo134** [comment]
galera boa noite, os numeros brancos do captcha se mexia antes ou começou agora

**Comment by Mikebriza** [comment]
Baixei o anaconda3 e instalei o torch, funcionou de buenas sem dar trabalho

**Comment by mauriciobsilva** [comment]
Aqui no ubuntu só instalou com o comando abaixo.

pip3 install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

**Comment by mauriciobsilva** [comment]
> meu erro é esse na VM > ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device é porque não tem espaço de disco será?

apaga os arquivos temporarios na pasta /tmp com o comando sudo rm -rf /tmp/*

**Comment by kerferber** [comment]
Funcionando aqui perfeitamente!

Meus agradecimentos ao @mpcabete, ao @Nucito e a todos que contribuíram. Abraços

**Comment by MaikonDosSantos** [comment]
alguem conseguiu rodar com alguma versão do python no windows 7 32bit?

**Comment by edurolim** [comment]
> > 
> 
> pow mano eu n conseguir usar no mac os não fiz uma vm
> 
> ![Captura de Tela 2021-12-11 às 22 07 04](https://user-images.githubusercontent.com/39178767/145696708-7d11a050-c762-46a0-b584-617680d46c77.png)

Mano, tem como fornecer o link do video ou de onde baixou o vware crackeaddo?

**Comment by chrisjardim** [comment]
> @rnesheiksilvestre o meu ta dando isso, ja instalei versao 3.8.x do python, uso o mac os ![Captura de Tela 2021-12-11 às 22 03 34](https://user-images.githubusercontent.com/95582054/145696623-6eb882df-e6c9-4eb6-9428-e0f05ea52d31.png) o

como faz pra rodar no mac?

**Comment by edurolim** [comment]
> > @rnesheiksilvestre o meu ta dando isso, ja instalei versao 3.8.x do python, uso o mac os ![Captura de Tela 2021-12-11 às 22 03 34](https://user-images.githubusercontent.com/95582054/145696623-6eb882df-e6c9-4eb6-9428-e0f05ea52d31.png) o
> 
> como faz pra rodar no mac?

pelo que entendi não está dando pra rodar no mac, voce tem que criar uma maquina virtual dentro do seu mac com o vmware fusion ou programa similar, e aí instalar um windows ou linux e rodar.

**Comment by rnesheiksilvestre** [comment]
> > > 
> > 
> > 
> > pow mano eu n conseguir usar no mac os não fiz uma vm
> > ![Captura de Tela 2021-12-11 às 22 07 04](https://user-images.githubusercontent.com/39178767/145696708-7d11a050-c762-46a0-b584-617680d46c77.png)
> 
> Mano, tem como fornecer o link do video ou de onde baixou o vware crackeaddo?

https://mactorrents.io/vmware-fusion-pro-12-1-2-build-17964953/

**Comment by henrique062** [comment]
as I understand it, python will no longer work on wincowns 7 right?

**Comment by Nucito** [comment]
> as I understand it, python will no longer work on wincowns 7 right?

To use this bot in windows 7 64 Bits you need install python 3.8.10

**Comment by henrique062** [comment]
> 
Thanks for the answer, but after doing all the installation as directed, the bot cannot do the captcha. 

![image](https://user-images.githubusercontent.com/95028031/145903591-0a7d8919-eeb9-4247-b46d-363f6d82aa80.png)

**Comment by chrisjardim** [comment]
> Boa noite galera
> 
> aqui da o seguinte depois de tudo instalado e estar na versão 3.9.6 do python, eis o problema: Traceback (most recent call last): File "C:\Users\Tony SSD\bombcrypto-bot\index.py", line 4, in from captcha.solveCaptcha import solveCaptcha File "C:\Users\Tony SSD\bombcrypto-bot\captcha\solveCaptcha.py", line 13, in model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local') AttributeError: module 'torch' has no attribute 'hub'
> 
> o que acham que pode ser? Ja reinstalei o Python em varias versões mas não vai

conseguiu resolver? to com o mesmo prpblema

**Comment by neurose0** [comment]
[2021-12-14 04:29:34] => ⬆️ Processing last action.....[[439 128 501  47]]
dig: , background_digits: 561
dig: , background_digits: 561
dig: , background_digits: 561
Traceback (most recent call last):
  File "C:\bomb\index.py", line 518, in <module>
    main()
  File "C:\bomb\index.py", line 486, in main
    solveCaptcha()
  File "C:\bomb\captcha\solveCaptcha.py", line 182, in solveCaptcha
    captcha_img = captchaImg(screenshot, popup_pos[0])
IndexError: tuple index out of range
