### ISSUE TITLE
Erro Inicialização 

### ISSUE THREAD

**Issue by Nzjj** [mpcabete/bombcrypto-bot#236]
```
Traceback (most recent call last):
  File "C:\bot\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bot\captcha\solveCaptcha.py", line 3, in <module>
    import pyautogui
  File "C:\Users\Abba 1\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py", line 546, in <module>
    from . import _pyautogui_win as platformModule
ImportError: cannot import name '_pyautogui_win' from partially initialized module 'pyautogui' (most likely due to a circular import) (C:\Users\Abba 1\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py)
```

Peguei a pasta que estava em uma maquina funcionando corretamente e coloquei em outras, e continuo o mesmo erro.

**Comment by Nzjj** [comment]
Todos os requirements.txt foram instalado sem apresentar nenhum erro.

**Comment by williamzzz1** [comment]
mesmo problema. conseguiu resolver?
