### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by andrguima** [mpcabete/bombcrypto-bot#295]
Esta dando este erro aaqui

File "C:\bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bomb\captcha\solveCaptcha.py", line 4, in <module>
    import mss
ModuleNotFoundError: No module named 'mss'

**Comment by M1D4SG0LD3N** [comment]
pip install -r requirements.txt

**Comment by Galinho90** [comment]
> pip install -r requirements.txt

Baixa as novas atualizações, e execute o:

pip install -r requirements.txt

**Comment by neurose0** [comment]
[2021-12-14 04:29:34] => ⬆️ Processing last action.....[[439 128 501  47]]
dig: , background_digits: 561
dig: , background_digits: 561
dig: , background_digits: 561
Traceback (most recent call last):
  File "C:\bomb\index.py", line 518, in <module>
    main()
  File "C:\bomb\index.py", line 486, in main
    solveCaptcha()
  File "C:\bomb\captcha\solveCaptcha.py", line 182, in solveCaptcha
    captcha_img = captchaImg(screenshot, popup_pos[0])
IndexError: tuple index out of range

**Comment by andrguima** [comment]
agora esta dando este

Traceback (most recent call last):
  File "C:\bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bomb\captcha\solveCaptcha.py", line 13, in <module>
    model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local')
AttributeError: module 'torch' has no attribute 'hub'
