### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by doranelle** [mpcabete/bombcrypto-bot#299]
Estou usando a última versão. O Bot nunca fica mais que umas 2 horas funcionando. Sempre para por algum erro no solvecaptha. Exemplo:

`Traceback (most recent call last):
  File "D:\Python\bombcrypto-bot-main\bombcrypto-bot-main\index.py", line 518, in <module>
    main()
  File "D:\Python\bombcrypto-bot-main\bombcrypto-bot-main\index.py", line 495, in main
    login()
  File "D:\Python\bombcrypto-bot-main\bombcrypto-bot-main\index.py", line 354, in login
    solveCaptcha()
  File "D:\Python\bombcrypto-bot-main\bombcrypto-bot-main\captcha\solveCaptcha.py", line 184, in solveCaptcha
    captcha_img = captchaImg(screenshot, popup_pos[0])
IndexError: tuple index out of range`

Alguém tem uma solução?

**Comment by BenitoMarculanoRibeiro** [comment]
Confere se a pasta targets está com todas as imagens.

**Comment by doranelle** [comment]
> Confere se a pasta targets está com todas as imagens.

Está sim :/ atualizei ela ontem mesmo
