### ISSUE TITLE
CAPTCHA ERROR 

### ISSUE THREAD

**Issue by Alekseyzhm** [mpcabete/bombcrypto-bot#356]
I updated the bot to the latest version and ran into a problem when the bot does not solve the captcha and exits in the following way. I also want to express my deep gratitude to the developers for the work done, thank you very much.

C:\Users\aleks\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
dig: , background_digits: None
dig: , background_digits: None
dig: , background_digits: None
dig: , background_digits: None
dig: , background_digits: None
.
[2021-12-17 09:53:43] => 💪 48 heroes sent to work
[2021-12-17 09:53:43] => ⬆️ Processing last action.....[[270 135 501  47]]
no slider

**Comment by kerferber** [comment]
Aqui aconteceu algo semelhante durante a madrugada.....

no captcha popup found!
720 samples taken in 25.76072072982788 seconds(27.9495285691415/s)
Processed 720 images in 0.948223352432251 seconds
Combined 720 images in 0.020476102828979492 seconds
background = 965
Traceback (most recent call last):
  File "C:\bomb\bomb3\index.py", line 528, in <module>
    main()
  File "C:\bomb\bomb3\index.py", line 505, in main
    login()
  File "C:\bomb\bomb3\index.py", line 364, in login
    solveCaptcha()
  File "C:\bomb\bomb3\captcha\solveCaptcha.py", line 297, in solveCaptcha
    slider_positions = getSliderPositions(screenshot, popup_pos)
  File "C:\bomb\bomb3\captcha\solveCaptcha.py", line 142, in getSliderPositions
    (end_x, end_y) = end
TypeError: cannot unpack non-iterable NoneType object

**Comment by Alekseyzhm** [comment]
Does anyone have a bot working ?!
