### ISSUE TITLE
.Xauthority error

### ISSUE THREAD

**Issue by s1k3ira** [mpcabete/bombcrypto-bot#383]
Guys, Tudo bem ? Estou tomando esse toco alguem sabe como resolver ?

root@a3e20cd6b536:~/bombcrypto-bot# python3 index.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Xlib/xauth.py", line 43, in __init__
    raw = open(filename, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/root/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "/root/bombcrypto-bot/captcha/solveCaptcha.py", line 3, in <module>
    import pyautogui
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.8/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 60, in __init__
    auth_name, auth_data = connect.get_auth(self.socket,
  File "/usr/local/lib/python3.8/dist-packages/Xlib/support/connect.py", line 91, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/support/unix_connect.py", line 103, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/local/lib/python3.8/dist-packages/Xlib/xauth.py", line 45, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/root/.Xauthority'

**Comment by fguide** [comment]
Aparentemente tem dois problemas, o primeiro é que está usando python 3.8.

O segundo é que falta o arquivo .Xauthority, você está usando VNC, docker ou algo do tipo?

**Comment by s1k3ira** [comment]
> Aparentemente tem dois problemas, o primeiro é que está usando python 3.8.
> 
> O segundo é que falta o arquivo .Xauthority, você está usando VNC, docker ou algo do tipo?
> 
> Edit: Se for VNC use o mesmo usuário que está rodando o vncserver para executar o script, mas antes exporte a var DISPLAY pro mesmo display da sessão VNC.

Exatamente ... estou usando uma imagen docker com VNC :)

**Comment by fguide** [comment]
Confere qual o usuário está rodando o vncserver no docker e use o mesmo para abrir o bot, se estiver rodando com root entao talvez tenha algo errado com o arquivo .Xauthority

**Comment by s1k3ira** [comment]
> Confere qual o usuário está rodando o vncserver no docker e use o mesmo para abrir o bot, se estiver rodando com root entao talvez tenha algo errado com o arquivo .Xauthority
> 
> Uma dúvida: você consegue acessar o VNC com ambiente grafico?

Acessa o modo grafico sim xD

**Comment by fguide** [comment]
e dentro do VNC vc consegue executar? Se conseguir e estiver tantando abrir de "fora" do vnc, precisa exportar o display correto do VNC antes
