### ISSUE TITLE
Bot can't login

### ISSUE THREAD

**Issue by Kikio1** [mpcabete/bombcrypto-bot#43]
When I try to login into the game and the bot clicks to connect to the wallet, then metamask window appears (select wallet) and the bot never clicks it.

I tried changing Images, but without success

Any help

Thanks

**Comment by Kikio1** [comment]
Another ussual bug:
 failSafeCheck()
  File "C:\Users\Mi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.

**Comment by Kikio1** [comment]
Checking if game has disconnected...Traceback (most recent call last):
  File "C:\bot\index.py", line 353, in <module>
    main()
  File "C:\bot\index.py", line 331, in main
    login()
  File "C:\bot\index.py", line 243, in login
    if clickBtn(sign_btn_img, name='sign button', timeout=8):
  File "C:\bot\index.py", line 113, in clickBtn
    pyautogui.moveTo(x+w/2,y+h/2,1)
  File "C:\Users\Mi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 597, in wrapper
    failSafeCheck()
  File "C:\Users\Mi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.

**Comment by lobomfz** [comment]
https://github.com/lobomfz/bombcrypto-bot
