### ISSUE TITLE
Erro ao iniciar com o comando "python index.py"

### ISSUE THREAD

**Issue by rbcazare** [mpcabete/bombcrypto-bot#490]
Não consigo iniciar o bot, fica com a seguinte mensagem:

Traceback (most recent call last):
  File "C:\bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bomb\captcha\solveCaptcha.py", line 3, in <module>
    import pyautogui
  File "C:\Users\Escritório\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'

**Comment by rodtanci** [comment]
Estou com mesmo erro, porém acusando "linha 7 coluna 3"

**Comment by rodtanci** [comment]
`
c:\bomb>python index.py
Traceback (most recent call last):
  File "index.py", line 7, in <module>
    from src.logger import logger, loggerMapClicked
  File "c:\bomb\src\logger.py", line 8, in <module>
    c = yaml.safe_load(stream)
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<block mapping
start>'
  in "./config.yaml", line 7, column 3`

**Comment by Yaagod** [comment]
1- Tá funcionando na versão mais recente do Python, 3.10.1, então usem ela que tá garantido que funciona.

2- Delete todos os pacotes do pip e instalem novamente:
Pasta: C:\Users\**Yago**\AppData\Local\Programs\Python\**Python310**\Lib\site-packages (mude o que está em negrito se necessário)
Para instalar novamente: pip install -r requirements.txt

**Comment by ricardoalesantiago** [comment]
> 1- Tá funcionando na versão mais recente do Python, 3.10.1, então usem ela que tá garantido que funciona.
> 
> 2- Delete todos os pacotes do pip e instalem novamente: Maneira mais rápida pra fazer isso, é deletar o conteúdo dessa pasta: C:\Users\**Yago**\AppData\Local\Programs\Python\**Python310**\Lib\site-packages (mude o que está em negrito se necessário e delete tudo que tá ai dentro) Para instalar os pacotes novamente: pip install -r requirements.txt

Não entendi o que é pra fazer e estou com o mesmo erro.
