### ISSUE TITLE
Erro ao iniciar bot: ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by Xymie** [mpcabete/bombcrypto-bot#641]
Traceback (most recent call last):
  File "C:\Users\arthur.apolinario\Documents\bomb\index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
  File "C:\Users\arthur.apolinario\Documents\bomb\src\logger.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by fguide** [comment]
#556
