### ISSUE TITLE
Erro bot nao roda

### ISSUE THREAD

**Issue by andremoller3** [mpcabete/bombcrypto-bot#66]
Tudo bem? poderia me ajudar neste erro? quando executo o bot aparece este erro abaixo, as vezes não aparece este erro, roda os comandos porem o cursos não se movimenta. se alguem puder me ajudar seria ótimo

Sending heroes to work...Traceback (most recent call last):
  File "C:\bomb\index.py", line 354, in <module>
    main()
  File "C:\bomb\index.py", line 325, in main
    refreshHeroes()
  File "C:\bomb\index.py", line 287, in refreshHeroes
    goToHeroes()
  File "C:\bomb\index.py", line 212, in goToHeroes
    clickBtn(hero_img)
  File "C:\bomb\index.py", line 113, in clickBtn
    pyautogui.moveTo(x+w/2,y+h/2,1)
  File "C:\Users\André Moller\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 611, in moveTo
    x, y = _unpackXY(x, y)
  File "C:\Users\André Moller\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 173, in _unpackXY
    if isinstance(x, collections.Sequence):
AttributeError: module 'collections' has no attribute 'Sequence'

**Comment by Samuray92** [comment]
Também estou com esse problema na minha vps
