### ISSUE TITLE
Não inicia no linux

### ISSUE THREAD

**Issue by Higt007** [mpcabete/bombcrypto-bot#681]
#511 Uso ele em uma VM ubuntu há certa de 1 mês porem tive que reiniciar a maquina depois disso não funcionou mai
>>---> Some configs can be found in the config.yaml file.
[2022-01-24 23:05:57] => 🏢 Search for heroes to work
[2022-01-24 23:05:57] => ⬆️ Processing last action..Traceback (most recent call last):
  File "/home/gus/Desktop/bomb/index.py", line 527, in <module>
    main()
  File "/home/gus/Desktop/bomb/index.py", line 496, in main
    refreshHeroes()
  File "/home/gus/Desktop/bomb/index.py", line 425, in refreshHeroes
    goToHeroes()
  File "/home/gus/Desktop/bomb/index.py", line 304, in goToHeroes
    if clickBtn(images['go-back-arrow']):
  File "/home/gus/Desktop/bomb/index.py", line 156, in clickBtn
    matches = positions(img, threshold=threshold)
  File "/home/gus/Desktop/bomb/index.py", line 183, in positions
    img = printSreen()
  File "/home/gus/Desktop/bomb/index.py", line 174, in printSreen
    sct_img = np.array(sct.grab(monitor))
  File "/home/gus/.local/lib/python3.9/site-packages/mss/base.py", line 88, in grab
    return self._grab_impl(monitor)
  File "/home/gus/.local/lib/python3.9/site-packages/mss/linux.py", line 446, in _grab_impl
    ximage = self.xlib.XGetImage(
  File "/home/gus/.local/lib/python3.9/site-packages/mss/linux.py", line 191, in validate
    raise ScreenShotError(err, details=details)
mss.exception.ScreenShotError: XGetImage() failed
****

**Comment by 1x10** [comment]
Qual é o Host e como você conecta na VM?

**Comment by fguide** [comment]
Deve ter atualizado e começado a utilizar o wayland, veja se não é o caso e se for, troque para o Xorg.

**Comment by fguide** [comment]
Em tempo, se estiver usando gnome, aparentemente instalar o gnome-screenshot resolve o problema.
