### ISSUE TITLE
Ubuntu 20.04 - Import PyAutoGUI problem

### ISSUE THREAD

**Issue by alanlucena** [mpcabete/bombcrypto-bot#694]
Galera, estou tentando utilizar o bot no linux, mas sempre ele da erro, detalhe, já fiz o passo a passo e instalei tudo do requirements.txt, mas mesmo asism ele fica dando erro na hora de executar, quando tentar importar o pyautogui;

```
Starting index.py
Traceback (most recent call last):
  File "index.py", line 9, in <module>
    import pyautogui
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.8/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
```

**Comment by fguide** [comment]
Problema com display, veja a thread #655
