### ISSUE TITLE
pyautogui.FailSafeException problem

### ISSUE THREAD

**Issue by fantasticaimer** [mpcabete/bombcrypto-bot#91]
Hi,

Thank you very much for all the work you are doing for this bot, it's a great job.
I have just one problem with the bot, I have the bot working on a VPS Windows Server 2022, and it works just fine. Sometimes when I connect to it, I find an error saying this: 
`Refreshing Heroes Positions.
.Traceback (most recent call last):
  File "C:\Users\fantastic\Documents\bombX\index.py", line 336, in <module>
    main()
  File "C:\Users\fantastic\Documents\bombX\index.py", line 327, in main
    refreshHeroesPositions()
  File "C:\Users\fantastic\Documents\bombX\index.py", line 207, in refreshHeroesPositions
    clickBtn(arrow_img)
  File "C:\Users\fantastic\Documents\bombX\index.py", line 94, in clickBtn
    pyautogui.moveTo(x+w/2,y+h/2,1)
  File "C:\Program Files\Python310\lib\site-packages\pyautogui\__init__.py", line 597, in wrapper
    failSafeCheck()
  File "C:\Program Files\Python310\lib\site-packages\pyautogui\__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.`

Can you help me with that please?

Thank you so much again for your great effort !

**Comment by Psicrow** [comment]
put this after de imports 

pydirectinput.FAILSAFE = False    
pyautogui.FAILSAFE = False
